// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cell: typeof import('./src/components/Cell.vue')['default']
    CellInput: typeof import('./src/components/CellInput.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sankey: typeof import('./src/components/Sankey.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
